name: livestream
description: LiveStream is a simple class which makes communication easy among different modules of your application.
version: 0.0.1
homepage: https://github.com/PatilShreyas/LiveStream-Flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
